/// Popular currencies offered in Settings → Currency (code, symbol, name).
const kPopularCurrencies = [
  (code: 'NPR', symbol: 'Rs', name: 'Nepali Rupee'),
  (code: 'USD', symbol: '\$', name: 'US Dollar'),
  (code: 'EUR', symbol: '€', name: 'Euro'),
  (code: 'GBP', symbol: '£', name: 'British Pound'),
  (code: 'INR', symbol: '₹', name: 'Indian Rupee'),
  (code: 'AUD', symbol: 'A\$', name: 'Australian Dollar'),
  (code: 'CAD', symbol: 'C\$', name: 'Canadian Dollar'),
  (code: 'SGD', symbol: 'S\$', name: 'Singapore Dollar'),
  (code: 'AED', symbol: 'AED', name: 'UAE Dirham'),
  (code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit'),
  (code: 'PHP', symbol: '₱', name: 'Philippine Peso'),
  (code: 'THB', symbol: '฿', name: 'Thai Baht'),
  (code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah'),
  (code: 'PKR', symbol: '₨', name: 'Pakistani Rupee'),
  (code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka'),
  (code: 'LKR', symbol: '₨', name: 'Sri Lankan Rupee'),
  (code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling'),
  (code: 'NGN', symbol: '₦', name: 'Nigerian Naira'),
  (code: 'ZAR', symbol: 'R', name: 'South African Rand'),
  (code: 'BRL', symbol: 'R\$', name: 'Brazilian Real'),
  (code: 'MXN', symbol: 'MX\$', name: 'Mexican Peso'),
  (code: 'JPY', symbol: '¥', name: 'Japanese Yen'),
  (code: 'CNY', symbol: '¥', name: 'Chinese Yuan'),
  (code: 'KRW', symbol: '₩', name: 'South Korean Won'),
];
